export const qLangs = {
  en: {
    // Language selection
    lang_select_title: 'Welcome to Modero',
    lang_select_subtitle: 'Please select your preferred language to begin the qualification process',
    lang_continue: 'Continue',

    // Progress step labels
    step_profile: 'Profile',
    step_personal: 'Personal',
    step_employment: 'Employment',
    step_documents: 'Documents',
    step_verification: 'Verification',
    step_financial: 'Financial',
    step_credit: 'Credit',
    step_complete: 'Complete',
    step_of: 'Step',
    of: 'of',

    // Step 1
    s1_title: 'Welcome! Begin your application process',
    s1_subtitle: 'You are just 8 steps away from qualifying for your apartment.',
    s1_linkedin: 'Continue with LinkedIn',
    s1_linkedin_done: 'LinkedIn Connected ✓',
    s1_xing: 'Continue with XING',
    s1_xing_done: 'XING Connected ✓',
    s1_facebook: 'Continue with Facebook',
    s1_facebook_done: 'Facebook Connected ✓',
    s1_or: 'OR',
    s1_first_name: 'First Name',
    s1_last_name: 'Last Name',
    s1_email: 'Email Address',
    s1_mobile: 'Mobile Number',
    s1_verify: 'Verify',
    s1_verified: 'Verified',
    s1_verifying: 'Verifying...',
    s1_continue: 'Continue to Qualification',
    s1_footer: "We'll guide you through the qualification process step by step",

    // Step 2
    s2_title: 'Personal Information',
    s2_subtitle: 'Tell us about yourself so we can verify your identity',
    s2_photo: 'Upload a profile photo (optional)',
    s2_first_name: 'First Name *',
    s2_last_name: 'Last Name *',
    s2_age: 'Age',
    s2_gender: 'Gender',
    s2_gender_placeholder: 'Select gender',
    s2_gender_male: 'Male',
    s2_gender_female: 'Female',
    s2_gender_other: 'Other',
    s2_gender_prefer: 'Prefer not to say',
    s2_nationality: 'Nationality *',
    s2_nationality_ph: 'e.g. Spanish',
    s2_pob: 'Place of Birth',
    s2_pob_ph: 'e.g. Madrid',
    s2_dni: 'DNI / NIE Number *',
    s2_dni_ph: 'e.g. 12345678A or X1234567B',
    s2_address: 'Address',
    s2_address_ph: 'Street and number',
    s2_city: 'City *',
    s2_city_ph: 'Barcelona',
    s2_postal: 'Postal Code',
    s2_postal_ph: '08001',
    s2_country: 'Country *',
    s2_country_ph: 'Spain',
    s2_next: 'Continue',
    s2_back: 'Back',

    // Step 3
    s3_title: 'Employment & Living',
    s3_subtitle: 'Help us understand your work situation and living needs',
    s3_emp_label: 'Employment Status *',
    s3_employed: '👔 Employed',
    s3_employed_desc: 'Working for a company',
    s3_self_employed: '💼 Self-Employed',
    s3_self_employed_desc: 'Running your own business',
    s3_student: '🎓 Student',
    s3_student_desc: 'Currently studying',
    s3_retired: '🏖️ Retired',
    s3_retired_desc: 'Receiving pension',
    s3_unemployed: '🔍 Unemployed',
    s3_unemployed_desc: 'Looking for work',
    s3_company: 'Company / Business Name',
    s3_company_ph: 'e.g. Acme Corp',
    s3_occupants: 'Number of Occupants',
    s3_person: 'person',
    s3_persons: 'persons',
    s3_will_live: 'will live in the apartment',
    s3_pets: 'Do you have pets?',
    s3_no_pets: '🚫 No pets',
    s3_yes_pets: '🐾 Yes, I have pets',
    s3_pets_ph: 'Describe your pet(s) — type, breed, size...',

    // Step 4
    s4_title: 'Upload Your Documents',
    s4_subtitle: 'Please upload the required documents to proceed with your application',
    s4_security: 'All files are encrypted and stored securely. Only authorized parties can access your documents.',
    s4_cv: 'CV / Resume',
    s4_cv_desc: 'Your most recent curriculum vitae',
    s4_payslip: 'Payslips',
    s4_payslip_desc: 'Last 3 months of payslips',
    s4_contract: 'Work Contract',
    s4_contract_desc: 'Employment or service contract',
    s4_id_doc: 'ID Document',
    s4_id_doc_desc: 'Passport, DNI, or NIE scan',
    s4_required: 'Required',
    s4_view: 'View uploaded file',
    s4_upload: 'Upload',
    s4_replace: 'Replace',
    s4_count: 'required documents uploaded',

    // Step 5
    s5_title: 'Identity Verification',
    s5_subtitle: 'We need to verify your identity and contact details',
    s5_gdpr: 'GDPR Consent *',
    s5_gdpr_desc: 'I consent to Modero processing my personal data for tenant qualification purposes in accordance with GDPR regulations.',
    s5_email_title: 'Email Verification',
    s5_email_desc: 'Confirm your email address',
    s5_send_code: 'Send Code',
    s5_sending: 'Sending...',
    s5_id_title: 'ID Verification (Identomat)',
    s5_id_desc: 'Secure identity check via document scan',
    s5_start_verification: 'Start Verification',
    s5_processing: 'Processing...',
    s5_biz_email_title: 'Business Email (Optional)',
    s5_biz_email_desc: 'Verify your work email for faster approval',
    s5_biz_email_ph: 'your@company.com',
    s5_biz_verifying: 'Verifying...',
    s5_biz_verify: 'Verify',
    s5_verified: 'Verified',
    s5_warning: 'Please complete GDPR consent, email verification, and ID verification to continue.',

    // Step 6
    s6_title: 'Financial Information',
    s6_subtitle: 'Provide your income details for the qualification assessment',
    s6_income: 'Monthly Net Income (€) *',
    s6_annual: 'Annual',
    s6_assessment: 'Income Assessment',
    s6_your_income: 'Your monthly income',
    s6_max_rent: 'Recommended max rent (40%)',
    s6_bank_title: 'Connect Bank Account',
    s6_bank_optional: 'Optional',
    s6_bank_desc: 'Automatically verify your income via PSD2 — speeds up approval',
    s6_bank_connected: 'Connected',
    s6_bank_connect: 'Connect',
    s6_bank_connecting: 'Connecting...',

    // Step 7
    s7_title: 'Credit Check & Financing',
    s7_subtitle: 'Final financial assessment — this step is required for qualification',
    s7_dnb: 'Dun & Bradstreet Credit Check',
    s7_dnb_sub: 'Authoritative credit risk assessment',
    s7_run: 'Run Credit Check',
    s7_running: 'Running assessment...',
    s7_out_of: 'out of 100',
    s7_completed: 'Credit check completed',
    s7_excellent: 'Excellent',
    s7_good: 'Good',
    s7_needs: 'Needs Improvement',
    s7_financing_title: 'Financing Options (Optional)',
    s7_financing_sub: "Select any financing options you'd like to explore for your rental",
    s7_submit: 'Submit Application',

    // Step 8
    s8_congrats: 'Congratulations',
    s8_submitted: 'Your application has been successfully submitted. Here\'s your qualification summary.',
    s8_score_label: 'Your Modero Qualification Score',
    s8_score_of: 'out of 100',
    s8_excellent: '⭐ Excellent profile — high approval likelihood',
    s8_good: '✅ Good profile — strong candidate',
    s8_review: '📋 Profile under review',
    s8_identity: 'Identity Verified',
    s8_email: 'Email Confirmed',
    s8_docs: 'Documents Submitted',
    s8_financial: 'Financial Profile',
    s8_credit: 'Credit Check',
    s8_gdpr: 'GDPR Consent',
    s8_review_title: 'Review in Progress',
    s8_review_desc: 'The landlord will review your application within 24-48 hours.',
    s8_email_title: 'Check Your Email',
    s8_email_desc: 'A confirmation has been sent to',
    s8_footer: 'Thank you for using Modero — your trusted rental qualification platform.',
  },

  es: {
    lang_select_title: 'Bienvenido a Modero',
    lang_select_subtitle: 'Por favor selecciona tu idioma preferido para comenzar el proceso de calificación',
    lang_continue: 'Continuar',

    step_profile: 'Perfil',
    step_personal: 'Personal',
    step_employment: 'Empleo',
    step_documents: 'Documentos',
    step_verification: 'Verificación',
    step_financial: 'Finanzas',
    step_credit: 'Crédito',
    step_complete: 'Completado',
    step_of: 'Paso',
    of: 'de',

    s1_title: '¡Bienvenido! Comienza tu proceso de solicitud',
    s1_subtitle: 'Estás a solo 8 pasos de calificar para tu apartamento.',
    s1_linkedin: 'Continuar con LinkedIn',
    s1_linkedin_done: 'LinkedIn Conectado ✓',
    s1_xing: 'Continuar con XING',
    s1_xing_done: 'XING Conectado ✓',
    s1_facebook: 'Continuar con Facebook',
    s1_facebook_done: 'Facebook Conectado ✓',
    s1_or: 'O',
    s1_first_name: 'Nombre',
    s1_last_name: 'Apellido',
    s1_email: 'Correo Electrónico',
    s1_mobile: 'Número de Móvil',
    s1_verify: 'Verificar',
    s1_verified: 'Verificado',
    s1_verifying: 'Verificando...',
    s1_continue: 'Continuar con la Calificación',
    s1_footer: 'Te guiaremos paso a paso por el proceso de calificación',

    s2_title: 'Información Personal',
    s2_subtitle: 'Cuéntanos sobre ti para que podamos verificar tu identidad',
    s2_photo: 'Sube una foto de perfil (opcional)',
    s2_first_name: 'Nombre *',
    s2_last_name: 'Apellido *',
    s2_age: 'Edad',
    s2_gender: 'Género',
    s2_gender_placeholder: 'Seleccionar género',
    s2_gender_male: 'Masculino',
    s2_gender_female: 'Femenino',
    s2_gender_other: 'Otro',
    s2_gender_prefer: 'Prefiero no decirlo',
    s2_nationality: 'Nacionalidad *',
    s2_nationality_ph: 'ej. Español',
    s2_pob: 'Lugar de Nacimiento',
    s2_pob_ph: 'ej. Madrid',
    s2_dni: 'Número DNI / NIE *',
    s2_dni_ph: 'ej. 12345678A o X1234567B',
    s2_address: 'Dirección',
    s2_address_ph: 'Calle y número',
    s2_city: 'Ciudad *',
    s2_city_ph: 'Barcelona',
    s2_postal: 'Código Postal',
    s2_postal_ph: '08001',
    s2_country: 'País *',
    s2_country_ph: 'España',
    s2_next: 'Continuar',
    s2_back: 'Atrás',

    s3_title: 'Empleo y Residencia',
    s3_subtitle: 'Ayúdanos a entender tu situación laboral y necesidades de vivienda',
    s3_emp_label: 'Situación Laboral *',
    s3_employed: '👔 Empleado',
    s3_employed_desc: 'Trabajando para una empresa',
    s3_self_employed: '💼 Autónomo',
    s3_self_employed_desc: 'Gestionando tu propio negocio',
    s3_student: '🎓 Estudiante',
    s3_student_desc: 'Actualmente estudiando',
    s3_retired: '🏖️ Jubilado',
    s3_retired_desc: 'Recibiendo pensión',
    s3_unemployed: '🔍 Desempleado',
    s3_unemployed_desc: 'En búsqueda de empleo',
    s3_company: 'Empresa / Nombre del Negocio',
    s3_company_ph: 'ej. Acme Corp',
    s3_occupants: 'Número de Ocupantes',
    s3_person: 'persona',
    s3_persons: 'personas',
    s3_will_live: 'vivirán en el apartamento',
    s3_pets: '¿Tienes mascotas?',
    s3_no_pets: '🚫 Sin mascotas',
    s3_yes_pets: '🐾 Sí, tengo mascotas',
    s3_pets_ph: 'Describe tu(s) mascota(s) — tipo, raza, tamaño...',

    s4_title: 'Sube tus Documentos',
    s4_subtitle: 'Por favor sube los documentos requeridos para continuar con tu solicitud',
    s4_security: 'Todos los archivos están cifrados y almacenados de forma segura. Solo las partes autorizadas pueden acceder a tus documentos.',
    s4_cv: 'CV / Currículum',
    s4_cv_desc: 'Tu currículum más reciente',
    s4_payslip: 'Nóminas',
    s4_payslip_desc: 'Últimas 3 nóminas',
    s4_contract: 'Contrato de Trabajo',
    s4_contract_desc: 'Contrato de empleo o servicios',
    s4_id_doc: 'Documento de Identidad',
    s4_id_doc_desc: 'Pasaporte, DNI o NIE escaneado',
    s4_required: 'Requerido',
    s4_view: 'Ver archivo subido',
    s4_upload: 'Subir',
    s4_replace: 'Reemplazar',
    s4_count: 'documentos requeridos subidos',

    s5_title: 'Verificación de Identidad',
    s5_subtitle: 'Necesitamos verificar tu identidad y datos de contacto',
    s5_gdpr: 'Consentimiento RGPD *',
    s5_gdpr_desc: 'Consiento que Modero procese mis datos personales para los fines de calificación de inquilinos de acuerdo con el RGPD.',
    s5_email_title: 'Verificación de Correo',
    s5_email_desc: 'Confirma tu dirección de correo electrónico',
    s5_send_code: 'Enviar Código',
    s5_sending: 'Enviando...',
    s5_id_title: 'Verificación de Identidad (Identomat)',
    s5_id_desc: 'Verificación de identidad segura mediante escaneo de documentos',
    s5_start_verification: 'Iniciar Verificación',
    s5_processing: 'Procesando...',
    s5_biz_email_title: 'Email Empresarial (Opcional)',
    s5_biz_email_desc: 'Verifica tu email de trabajo para una aprobación más rápida',
    s5_biz_email_ph: 'tu@empresa.com',
    s5_biz_verifying: 'Verificando...',
    s5_biz_verify: 'Verificar',
    s5_verified: 'Verificado',
    s5_warning: 'Por favor completa el consentimiento RGPD, la verificación de correo y la verificación de identidad para continuar.',

    s6_title: 'Información Financiera',
    s6_subtitle: 'Proporciona tus datos de ingresos para la evaluación de calificación',
    s6_income: 'Ingresos Netos Mensuales (€) *',
    s6_annual: 'Anual',
    s6_assessment: 'Evaluación de Ingresos',
    s6_your_income: 'Tus ingresos mensuales',
    s6_max_rent: 'Alquiler máximo recomendado (40%)',
    s6_bank_title: 'Conectar Cuenta Bancaria',
    s6_bank_optional: 'Opcional',
    s6_bank_desc: 'Verifica automáticamente tus ingresos vía PSD2 — acelera la aprobación',
    s6_bank_connected: 'Conectado',
    s6_bank_connect: 'Conectar',
    s6_bank_connecting: 'Conectando...',

    s7_title: 'Verificación Crediticia y Financiación',
    s7_subtitle: 'Evaluación financiera final — este paso es obligatorio para la calificación',
    s7_dnb: 'Verificación Crediticia Dun & Bradstreet',
    s7_dnb_sub: 'Evaluación de riesgo crediticio autorizada',
    s7_run: 'Iniciar Verificación',
    s7_running: 'Ejecutando evaluación...',
    s7_out_of: 'de 100',
    s7_completed: 'Verificación crediticia completada',
    s7_excellent: 'Excelente',
    s7_good: 'Bueno',
    s7_needs: 'Necesita Mejora',
    s7_financing_title: 'Opciones de Financiación (Opcional)',
    s7_financing_sub: 'Selecciona las opciones de financiación que te gustaría explorar para tu alquiler',
    s7_submit: 'Enviar Solicitud',

    s8_congrats: 'Felicitaciones',
    s8_submitted: 'Tu solicitud ha sido enviada con éxito. Aquí está tu resumen de calificación.',
    s8_score_label: 'Tu Puntuación de Calificación Modero',
    s8_score_of: 'de 100',
    s8_excellent: '⭐ Perfil excelente — alta probabilidad de aprobación',
    s8_good: '✅ Buen perfil — candidato sólido',
    s8_review: '📋 Perfil en revisión',
    s8_identity: 'Identidad Verificada',
    s8_email: 'Correo Confirmado',
    s8_docs: 'Documentos Enviados',
    s8_financial: 'Perfil Financiero',
    s8_credit: 'Verificación Crediticia',
    s8_gdpr: 'Consentimiento RGPD',
    s8_review_title: 'Revisión en Proceso',
    s8_review_desc: 'El propietario revisará tu solicitud en 24-48 horas.',
    s8_email_title: 'Revisa tu Correo',
    s8_email_desc: 'Se ha enviado una confirmación a',
    s8_footer: 'Gracias por usar Modero — tu plataforma de calificación de alquiler de confianza.',
  },

  pt: {
    lang_select_title: 'Bem-vindo ao Modero',
    lang_select_subtitle: 'Por favor selecione o seu idioma preferido para começar o processo de qualificação',
    lang_continue: 'Continuar',

    step_profile: 'Perfil',
    step_personal: 'Pessoal',
    step_employment: 'Emprego',
    step_documents: 'Documentos',
    step_verification: 'Verificação',
    step_financial: 'Finanças',
    step_credit: 'Crédito',
    step_complete: 'Concluído',
    step_of: 'Passo',
    of: 'de',

    s1_title: 'Bem-vindo! Comece o seu processo de candidatura',
    s1_subtitle: 'Está a apenas 8 passos de se qualificar para o seu apartamento.',
    s1_linkedin: 'Continuar com LinkedIn',
    s1_linkedin_done: 'LinkedIn Conectado ✓',
    s1_xing: 'Continuar com XING',
    s1_xing_done: 'XING Conectado ✓',
    s1_facebook: 'Continuar com Facebook',
    s1_facebook_done: 'Facebook Conectado ✓',
    s1_or: 'OU',
    s1_first_name: 'Nome',
    s1_last_name: 'Apelido',
    s1_email: 'Endereço de Email',
    s1_mobile: 'Número de Telemóvel',
    s1_verify: 'Verificar',
    s1_verified: 'Verificado',
    s1_verifying: 'A verificar...',
    s1_continue: 'Continuar para Qualificação',
    s1_footer: 'Iremos guiá-lo passo a passo pelo processo de qualificação',

    s2_title: 'Informação Pessoal',
    s2_subtitle: 'Fale-nos sobre si para que possamos verificar a sua identidade',
    s2_photo: 'Carregar uma foto de perfil (opcional)',
    s2_first_name: 'Nome *',
    s2_last_name: 'Apelido *',
    s2_age: 'Idade',
    s2_gender: 'Género',
    s2_gender_placeholder: 'Selecionar género',
    s2_gender_male: 'Masculino',
    s2_gender_female: 'Feminino',
    s2_gender_other: 'Outro',
    s2_gender_prefer: 'Prefiro não dizer',
    s2_nationality: 'Nacionalidade *',
    s2_nationality_ph: 'ex. Português',
    s2_pob: 'Local de Nascimento',
    s2_pob_ph: 'ex. Lisboa',
    s2_dni: 'Número BI / NIF *',
    s2_dni_ph: 'ex. 12345678A',
    s2_address: 'Morada',
    s2_address_ph: 'Rua e número',
    s2_city: 'Cidade *',
    s2_city_ph: 'Lisboa',
    s2_postal: 'Código Postal',
    s2_postal_ph: '1000-001',
    s2_country: 'País *',
    s2_country_ph: 'Portugal',
    s2_next: 'Continuar',
    s2_back: 'Voltar',

    s3_title: 'Emprego e Residência',
    s3_subtitle: 'Ajude-nos a compreender a sua situação laboral e necessidades de habitação',
    s3_emp_label: 'Situação Profissional *',
    s3_employed: '👔 Empregado',
    s3_employed_desc: 'A trabalhar para uma empresa',
    s3_self_employed: '💼 Trabalhador Independente',
    s3_self_employed_desc: 'Gerindo o seu próprio negócio',
    s3_student: '🎓 Estudante',
    s3_student_desc: 'Atualmente a estudar',
    s3_retired: '🏖️ Reformado',
    s3_retired_desc: 'A receber pensão',
    s3_unemployed: '🔍 Desempregado',
    s3_unemployed_desc: 'À procura de trabalho',
    s3_company: 'Empresa / Nome do Negócio',
    s3_company_ph: 'ex. Acme Corp',
    s3_occupants: 'Número de Ocupantes',
    s3_person: 'pessoa',
    s3_persons: 'pessoas',
    s3_will_live: 'vão viver no apartamento',
    s3_pets: 'Tem animais de estimação?',
    s3_no_pets: '🚫 Sem animais',
    s3_yes_pets: '🐾 Sim, tenho animais',
    s3_pets_ph: 'Descreva o(s) seu(s) animal(ais) — tipo, raça, tamanho...',

    s4_title: 'Carregar os seus Documentos',
    s4_subtitle: 'Por favor carregue os documentos necessários para prosseguir com a sua candidatura',
    s4_security: 'Todos os ficheiros são encriptados e armazenados de forma segura. Apenas as partes autorizadas podem aceder aos seus documentos.',
    s4_cv: 'CV / Currículo',
    s4_cv_desc: 'O seu currículo mais recente',
    s4_payslip: 'Recibos de Vencimento',
    s4_payslip_desc: 'Últimos 3 recibos de vencimento',
    s4_contract: 'Contrato de Trabalho',
    s4_contract_desc: 'Contrato de emprego ou serviços',
    s4_id_doc: 'Documento de Identidade',
    s4_id_doc_desc: 'Passaporte, BI ou NIF digitalizado',
    s4_required: 'Obrigatório',
    s4_view: 'Ver ficheiro carregado',
    s4_upload: 'Carregar',
    s4_replace: 'Substituir',
    s4_count: 'documentos obrigatórios carregados',

    s5_title: 'Verificação de Identidade',
    s5_subtitle: 'Precisamos de verificar a sua identidade e dados de contacto',
    s5_gdpr: 'Consentimento RGPD *',
    s5_gdpr_desc: 'Consinto que a Modero processe os meus dados pessoais para fins de qualificação de inquilinos de acordo com o RGPD.',
    s5_email_title: 'Verificação de Email',
    s5_email_desc: 'Confirme o seu endereço de email',
    s5_send_code: 'Enviar Código',
    s5_sending: 'A enviar...',
    s5_id_title: 'Verificação de Identidade (Identomat)',
    s5_id_desc: 'Verificação de identidade segura através de digitalização de documentos',
    s5_start_verification: 'Iniciar Verificação',
    s5_processing: 'A processar...',
    s5_biz_email_title: 'Email Profissional (Opcional)',
    s5_biz_email_desc: 'Verifique o seu email de trabalho para aprovação mais rápida',
    s5_biz_email_ph: 'o.seu@empresa.pt',
    s5_biz_verifying: 'A verificar...',
    s5_biz_verify: 'Verificar',
    s5_verified: 'Verificado',
    s5_warning: 'Por favor complete o consentimento RGPD, a verificação de email e a verificação de identidade para continuar.',

    s6_title: 'Informação Financeira',
    s6_subtitle: 'Forneça os seus dados de rendimento para a avaliação de qualificação',
    s6_income: 'Rendimento Líquido Mensal (€) *',
    s6_annual: 'Anual',
    s6_assessment: 'Avaliação de Rendimento',
    s6_your_income: 'O seu rendimento mensal',
    s6_max_rent: 'Renda máxima recomendada (40%)',
    s6_bank_title: 'Conectar Conta Bancária',
    s6_bank_optional: 'Opcional',
    s6_bank_desc: 'Verifique automaticamente o seu rendimento via PSD2 — acelera a aprovação',
    s6_bank_connected: 'Conectado',
    s6_bank_connect: 'Conectar',
    s6_bank_connecting: 'A conectar...',

    s7_title: 'Verificação de Crédito e Financiamento',
    s7_subtitle: 'Avaliação financeira final — este passo é obrigatório para a qualificação',
    s7_dnb: 'Verificação de Crédito Dun & Bradstreet',
    s7_dnb_sub: 'Avaliação de risco de crédito autorizada',
    s7_run: 'Executar Verificação de Crédito',
    s7_running: 'A executar avaliação...',
    s7_out_of: 'de 100',
    s7_completed: 'Verificação de crédito concluída',
    s7_excellent: 'Excelente',
    s7_good: 'Bom',
    s7_needs: 'Precisa de Melhoria',
    s7_financing_title: 'Opções de Financiamento (Opcional)',
    s7_financing_sub: 'Selecione as opções de financiamento que gostaria de explorar para o seu arrendamento',
    s7_submit: 'Submeter Candidatura',

    s8_congrats: 'Parabéns',
    s8_submitted: 'A sua candidatura foi submetida com sucesso. Aqui está o seu resumo de qualificação.',
    s8_score_label: 'A sua Pontuação de Qualificação Modero',
    s8_score_of: 'de 100',
    s8_excellent: '⭐ Perfil excelente — alta probabilidade de aprovação',
    s8_good: '✅ Bom perfil — candidato forte',
    s8_review: '📋 Perfil em revisão',
    s8_identity: 'Identidade Verificada',
    s8_email: 'Email Confirmado',
    s8_docs: 'Documentos Submetidos',
    s8_financial: 'Perfil Financeiro',
    s8_credit: 'Verificação de Crédito',
    s8_gdpr: 'Consentimento RGPD',
    s8_review_title: 'Revisão em Curso',
    s8_review_desc: 'O proprietário irá rever a sua candidatura nas próximas 24-48 horas.',
    s8_email_title: 'Verifique o seu Email',
    s8_email_desc: 'Uma confirmação foi enviada para',
    s8_footer: 'Obrigado por usar o Modero — a sua plataforma de qualificação de arrendamento de confiança.',
  },

  it: {
    lang_select_title: 'Benvenuto in Modero',
    lang_select_subtitle: 'Seleziona la tua lingua preferita per iniziare il processo di qualificazione',
    lang_continue: 'Continua',

    step_profile: 'Profilo',
    step_personal: 'Personale',
    step_employment: 'Impiego',
    step_documents: 'Documenti',
    step_verification: 'Verifica',
    step_financial: 'Finanziario',
    step_credit: 'Credito',
    step_complete: 'Completato',
    step_of: 'Passo',
    of: 'di',

    s1_title: 'Benvenuto! Inizia il tuo processo di candidatura',
    s1_subtitle: 'Sei a soli 8 passi dalla qualificazione per il tuo appartamento.',
    s1_linkedin: 'Continua con LinkedIn',
    s1_linkedin_done: 'LinkedIn Collegato ✓',
    s1_xing: 'Continua con XING',
    s1_xing_done: 'XING Collegato ✓',
    s1_facebook: 'Continua con Facebook',
    s1_facebook_done: 'Facebook Collegato ✓',
    s1_or: 'O',
    s1_first_name: 'Nome',
    s1_last_name: 'Cognome',
    s1_email: 'Indirizzo Email',
    s1_mobile: 'Numero di Cellulare',
    s1_verify: 'Verifica',
    s1_verified: 'Verificato',
    s1_verifying: 'In verifica...',
    s1_continue: 'Continua con la Qualificazione',
    s1_footer: 'Ti guideremo passo dopo passo attraverso il processo di qualificazione',

    s2_title: 'Informazioni Personali',
    s2_subtitle: 'Raccontaci di te per poter verificare la tua identità',
    s2_photo: 'Carica una foto profilo (facoltativo)',
    s2_first_name: 'Nome *',
    s2_last_name: 'Cognome *',
    s2_age: 'Età',
    s2_gender: 'Genere',
    s2_gender_placeholder: 'Seleziona genere',
    s2_gender_male: 'Maschile',
    s2_gender_female: 'Femminile',
    s2_gender_other: 'Altro',
    s2_gender_prefer: 'Preferisco non dirlo',
    s2_nationality: 'Nazionalità *',
    s2_nationality_ph: 'es. Italiano',
    s2_pob: 'Luogo di Nascita',
    s2_pob_ph: 'es. Roma',
    s2_dni: 'Numero Codice Fiscale / Carta d\'identità *',
    s2_dni_ph: 'es. RSSMRA85M01H501Z',
    s2_address: 'Indirizzo',
    s2_address_ph: 'Via e numero',
    s2_city: 'Città *',
    s2_city_ph: 'Milano',
    s2_postal: 'Codice Postale',
    s2_postal_ph: '20100',
    s2_country: 'Paese *',
    s2_country_ph: 'Italia',
    s2_next: 'Continua',
    s2_back: 'Indietro',

    s3_title: 'Impiego e Abitazione',
    s3_subtitle: 'Aiutaci a capire la tua situazione lavorativa e le tue esigenze abitative',
    s3_emp_label: 'Stato Occupazionale *',
    s3_employed: '👔 Dipendente',
    s3_employed_desc: 'Lavoro per un\'azienda',
    s3_self_employed: '💼 Lavoratore Autonomo',
    s3_self_employed_desc: 'Gestisco la mia attività',
    s3_student: '🎓 Studente',
    s3_student_desc: 'Attualmente in formazione',
    s3_retired: '🏖️ Pensionato',
    s3_retired_desc: 'Percepisco una pensione',
    s3_unemployed: '🔍 Disoccupato',
    s3_unemployed_desc: 'In cerca di lavoro',
    s3_company: 'Azienda / Nome dell\'Attività',
    s3_company_ph: 'es. Acme Corp',
    s3_occupants: 'Numero di Occupanti',
    s3_person: 'persona',
    s3_persons: 'persone',
    s3_will_live: 'abiteranno nell\'appartamento',
    s3_pets: 'Hai animali domestici?',
    s3_no_pets: '🚫 Nessun animale',
    s3_yes_pets: '🐾 Sì, ho animali',
    s3_pets_ph: 'Descrivi il/i tuo/i animale/i — tipo, razza, taglia...',

    s4_title: 'Carica i tuoi Documenti',
    s4_subtitle: 'Carica i documenti richiesti per procedere con la tua candidatura',
    s4_security: 'Tutti i file sono crittografati e archiviati in modo sicuro. Solo le parti autorizzate possono accedere ai tuoi documenti.',
    s4_cv: 'CV / Curriculum',
    s4_cv_desc: 'Il tuo curriculum più recente',
    s4_payslip: 'Buste Paga',
    s4_payslip_desc: 'Ultime 3 buste paga',
    s4_contract: 'Contratto di Lavoro',
    s4_contract_desc: 'Contratto di lavoro o di servizi',
    s4_id_doc: 'Documento d\'Identità',
    s4_id_doc_desc: 'Passaporto, carta d\'identità o codice fiscale scansionato',
    s4_required: 'Obbligatorio',
    s4_view: 'Visualizza file caricato',
    s4_upload: 'Carica',
    s4_replace: 'Sostituisci',
    s4_count: 'documenti obbligatori caricati',

    s5_title: 'Verifica dell\'Identità',
    s5_subtitle: 'Dobbiamo verificare la tua identità e i dati di contatto',
    s5_gdpr: 'Consenso GDPR *',
    s5_gdpr_desc: 'Acconsento che Modero tratti i miei dati personali per scopi di qualificazione degli inquilini in conformità con il GDPR.',
    s5_email_title: 'Verifica Email',
    s5_email_desc: 'Conferma il tuo indirizzo email',
    s5_send_code: 'Invia Codice',
    s5_sending: 'Invio in corso...',
    s5_id_title: 'Verifica Identità (Identomat)',
    s5_id_desc: 'Verifica dell\'identità sicura tramite scansione documenti',
    s5_start_verification: 'Avvia Verifica',
    s5_processing: 'Elaborazione...',
    s5_biz_email_title: 'Email Aziendale (Facoltativo)',
    s5_biz_email_desc: 'Verifica la tua email di lavoro per un\'approvazione più rapida',
    s5_biz_email_ph: 'tuo@azienda.it',
    s5_biz_verifying: 'Verifica in corso...',
    s5_biz_verify: 'Verifica',
    s5_verified: 'Verificato',
    s5_warning: 'Completa il consenso GDPR, la verifica email e la verifica identità per continuare.',

    s6_title: 'Informazioni Finanziarie',
    s6_subtitle: 'Fornisci i dettagli del tuo reddito per la valutazione di qualificazione',
    s6_income: 'Reddito Netto Mensile (€) *',
    s6_annual: 'Annuale',
    s6_assessment: 'Valutazione del Reddito',
    s6_your_income: 'Il tuo reddito mensile',
    s6_max_rent: 'Affitto massimo consigliato (40%)',
    s6_bank_title: 'Collega Conto Bancario',
    s6_bank_optional: 'Facoltativo',
    s6_bank_desc: 'Verifica automaticamente il tuo reddito via PSD2 — accelera l\'approvazione',
    s6_bank_connected: 'Collegato',
    s6_bank_connect: 'Collega',
    s6_bank_connecting: 'Connessione...',

    s7_title: 'Verifica del Credito e Finanziamento',
    s7_subtitle: 'Valutazione finanziaria finale — questo passaggio è obbligatorio per la qualificazione',
    s7_dnb: 'Verifica Credito Dun & Bradstreet',
    s7_dnb_sub: 'Valutazione autorizzata del rischio creditizio',
    s7_run: 'Esegui Verifica Credito',
    s7_running: 'Esecuzione valutazione...',
    s7_out_of: 'su 100',
    s7_completed: 'Verifica del credito completata',
    s7_excellent: 'Eccellente',
    s7_good: 'Buono',
    s7_needs: 'Da Migliorare',
    s7_financing_title: 'Opzioni di Finanziamento (Facoltativo)',
    s7_financing_sub: 'Seleziona le opzioni di finanziamento che desideri esplorare per il tuo affitto',
    s7_submit: 'Invia Candidatura',

    s8_congrats: 'Congratulazioni',
    s8_submitted: 'La tua candidatura è stata inviata con successo. Ecco il tuo riepilogo di qualificazione.',
    s8_score_label: 'Il tuo Punteggio di Qualificazione Modero',
    s8_score_of: 'su 100',
    s8_excellent: '⭐ Profilo eccellente — alta probabilità di approvazione',
    s8_good: '✅ Buon profilo — candidato solido',
    s8_review: '📋 Profilo in revisione',
    s8_identity: 'Identità Verificata',
    s8_email: 'Email Confermata',
    s8_docs: 'Documenti Inviati',
    s8_financial: 'Profilo Finanziario',
    s8_credit: 'Verifica del Credito',
    s8_gdpr: 'Consenso GDPR',
    s8_review_title: 'Revisione in Corso',
    s8_review_desc: 'Il proprietario esaminerà la tua candidatura entro 24-48 ore.',
    s8_email_title: 'Controlla la tua Email',
    s8_email_desc: 'Una conferma è stata inviata a',
    s8_footer: 'Grazie per aver utilizzato Modero — la tua piattaforma di qualificazione affitti di fiducia.',
  },
};