import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    my_account: 'My Account', edit_profile: 'Edit Profile', settings: 'Settings',
    logout: 'Logout', login: 'Login',
    my_properties: 'My Properties', recent_inquiries: 'Recent Inquiries',
    status_new: 'New', status_screening: 'Screening', status_kyc_pending: 'KYC Pending',
    status_qualified: 'Qualified', status_rejected: 'Rejected', status_rented: 'Rented',
    tenant_profile: 'Tenant Profile', landlord_decision: 'Landlord Decision',
    review_approve_desc: 'Review and approve/reject this application',
    application_progress: 'Application Progress', personal_information: 'Personal Information',
    id_verification: 'ID Verification', connected_profiles: 'Connected Profiles',
    employment_information: 'Employment Information', financial_information: 'Financial Information',
    income_verification: 'Income Verification', required_documents: 'Required Documents',
    credit_check: 'Credit Check', financing_options: 'Financing Options',
    internal_notes: 'Internal Notes', save_notes: 'Save Notes',
    approve: 'Approve', reject: 'Reject', pending: 'Pending',
    property_information: 'Property Information', performance_metrics: 'Performance Metrics',
    rental_funnel: 'Rental Funnel',
    view_document: 'View Document', upload: 'Upload', uploading: 'Uploading...',
    no_inquiries: 'No inquiries yet', connect_bank: 'Connect Bank Account',
    bank_connected: 'Bank Account Connected',
    funnel_inquiry: 'Inquiry Received', funnel_verification: 'Verification in Progress',
    funnel_qualified: 'Qualified', funnel_approved: 'Approved', funnel_rejected: 'Rejected',
    modero_score: 'Modero Qualification Score', overall_rating: 'Overall tenant qualification rating',
    add_notes_placeholder: 'Add internal notes about this tenant...',
    notes_saved: 'Notes saved successfully',
    in_screening: 'In Screening', conversion_rate: 'Conversion Rate',
    address: 'Address', city: 'City', monthly_rent: 'Monthly Rent', bedrooms: 'Bedrooms',
    idealista_id: 'Idealista ID', total_inquiries: 'Total Inquiries',
    // Dashboard
    filter_by_status: 'Filter by status', all_inquiries: 'All Inquiries',
    active_properties: 'Active Properties', qualified_tenants_label: 'Qualified Tenants',
    verification_rate: 'Verification Rate', total_listings: 'total listings',
    avg_per_property: 'avg per property', verified_tenants: 'verified tenants',
    vs_last_month: 'vs last month',
    // InquiryFunnel
    inquiry_pipeline: 'Inquiry Pipeline', tenant_qualification_funnel: 'Tenant qualification funnel',
    // PropertyPerformance
    click_property_details: 'Click a property to view details',
    property_label: 'Property', rent: 'Rent', inquiries_label: 'Inquiries',
    conversion: 'Conversion', no_properties: 'No properties yet',
    // RevenueChart
    qualification_trends: 'Qualification Trends',
    monthly_qualification_metrics: 'Monthly tenant qualification metrics',
    screened_label: 'Screened',
    // RecentInquiries
    tenant_label: 'Tenant', contact: 'Contact', income: 'Income',
    score: 'Score', status_label: 'Status', date_label: 'Date',
    // TenantDetailsDialog
    excellent: 'Excellent', good: 'Good', needs_review: 'Needs Review',
    not_connected: 'Not connected', connected_label: 'Connected',
    employment_verification: 'Employment verification',
    employment_status_label: 'Employment Status', company_label: 'Company',
    business_email_label: 'Business Email', monthly_income_label: 'Monthly Income',
    income_ratio_label: 'Income Ratio', credit_score_label: 'Credit Score',
    occupants_label: 'Occupants', pets_label: 'Pets',
    connect_bank_desc: 'Connect bank account to automatically verify monthly income',
    bank_verified: 'Status: Verified ✓', bank_pending: 'Pending verification',
    cv_resume: 'CV / Resume', payslips_label: 'Payslips',
    work_contract: 'Work Contract', id_document: 'ID Document',
    uploaded: '✓ Uploaded', credit_verification: 'Credit Verification',
    db_assessment: 'Dun & Bradstreet assessment',
    step1_label: 'Initial Contact', step1_desc: 'First inquiry received',
    step2_label: 'Document Upload', step2_desc: 'Documents submitted',
    step3_label: 'ID Verification', step3_desc: 'Identity confirmed',
    step4_label: 'Financial Check', step4_desc: 'Income & credit verified',
    step5_label: 'Final Review', step5_desc: 'Ready for decision',
    healthy: 'Healthy', high_ratio: 'High', target_ratio: 'Target: <40%',
    financing_recommended: 'financing recommended to tenant', clear_label: 'Clear',
    tenant_qualified_label: 'Tenant Qualified',
    klarna_desc1: 'Buy now, pay later', klarna_desc2: 'Flexible instalments',
    santander_desc1: 'Personal financing', santander_desc2: 'Competitive rates',
    place_of_birth_label: 'Place of Birth', dni_nie_label: 'DNI/NIE Number',
    postal_code_label: 'Postal Code', country_label: 'Country',
    gdpr_label: 'GDPR Verified', verified_status: 'Verified',
    // PropertyDetailsDialog
    responsible_agent: 'Responsible Real Estate Agent',
    name_label: 'Name', agency_label: 'Agency', mobile_label: 'Mobile',
    email_label: 'Email', approved_rented: 'Approved / Rented',
    property_status_label: 'Status',
    rental_contracts: 'Rental Contracts',
    contracts_subtitle: 'Create, manage, and send rental contracts for signature',
    create_new_contract: 'Create New Contract',
    select_tenant: 'Select Tenant',
    lease_start_date: 'Lease Start Date',
    lease_end_date: 'Lease End Date',
    security_deposit: 'Security Deposit (€)',
    contract_terms: 'Contract Terms & Conditions',
    customize_template: 'You can customize the template or use the default terms.',
    create_contract: 'Create Contract',
    creating_contract: 'Creating...',
    cancel: 'Cancel',
    lease_period: 'Lease Period',
    tenant_signature_label: 'Tenant Signature',
    landlord_signature_label: 'Landlord Signature',
    send_for_signature: 'Send for Signature',
    sending: 'Sending...',
    awaiting_your_signature: 'Awaiting Your Signature',
    sign_rental_contract: 'Sign Rental Contract',
    sign_contract_header: 'Property',
    contract_terms_label: 'Contract Terms',
    your_signature: 'Your Signature',
    type_full_name: 'Type Your Full Name',
    enter_full_name: 'Enter your full name',
    your_signature_preview: 'Your signature appears here',
    sign_contract_btn: 'Sign Contract',
    signing_contract: 'Signing...',
    contract_signed_success: 'Contract Signed Successfully!',
    tenant_will_sign_next: 'The landlord will now need to review and sign the contract.',
    both_parties_signed: 'Both parties have now signed the contract. It is legally binding.',
    contract_not_found: 'Contract not found. Please check your signing link.',
    signature_status: 'Signature Status',
    tenant: 'Tenant',
    landlord: 'Landlord',
    already_signed: 'Already Signed',
    you_have_signed: 'You have already signed this contract. Awaiting the other party to complete.',
    },
    es: {
    my_account: 'Mi Cuenta', edit_profile: 'Editar Perfil', settings: 'Configuración',
    logout: 'Cerrar Sesión', login: 'Iniciar Sesión',
    my_properties: 'Mis Propiedades', recent_inquiries: 'Solicitudes Recientes',
    status_new: 'Nuevo', status_screening: 'En Revisión', status_kyc_pending: 'KYC Pendiente',
    status_qualified: 'Calificado', status_rejected: 'Rechazado', status_rented: 'Alquilado',
    tenant_profile: 'Perfil del Inquilino', landlord_decision: 'Decisión del Propietario',
    review_approve_desc: 'Revisar y aprobar/rechazar esta solicitud',
    application_progress: 'Progreso de Solicitud', personal_information: 'Información Personal',
    id_verification: 'Verificación de Identidad', connected_profiles: 'Perfiles Conectados',
    employment_information: 'Información Laboral', financial_information: 'Información Financiera',
    income_verification: 'Verificación de Ingresos', required_documents: 'Documentos Requeridos',
    credit_check: 'Verificación Crediticia', financing_options: 'Opciones de Financiación',
    internal_notes: 'Notas Internas', save_notes: 'Guardar Notas',
    approve: 'Aprobar', reject: 'Rechazar', pending: 'Pendiente',
    property_information: 'Información de Propiedad', performance_metrics: 'Métricas de Rendimiento',
    rental_funnel: 'Embudo de Alquiler',
    view_document: 'Ver Documento', upload: 'Subir', uploading: 'Subiendo...',
    no_inquiries: 'Sin solicitudes aún', connect_bank: 'Conectar Cuenta Bancaria',
    bank_connected: 'Cuenta Bancaria Conectada',
    funnel_inquiry: 'Solicitud Recibida', funnel_verification: 'Verificación en Curso',
    funnel_qualified: 'Calificado', funnel_approved: 'Aprobado', funnel_rejected: 'Rechazado',
    modero_score: 'Puntuación de Calificación Modero', overall_rating: 'Calificación general del inquilino',
    add_notes_placeholder: 'Agregar notas internas sobre este inquilino...',
    notes_saved: 'Notas guardadas correctamente',
    in_screening: 'En Revisión', conversion_rate: 'Tasa de Conversión',
    address: 'Dirección', city: 'Ciudad', monthly_rent: 'Renta Mensual', bedrooms: 'Habitaciones',
    idealista_id: 'ID Idealista', total_inquiries: 'Total Solicitudes',
    filter_by_status: 'Filtrar por estado', all_inquiries: 'Todas las Solicitudes',
    active_properties: 'Propiedades Activas', qualified_tenants_label: 'Inquilinos Calificados',
    verification_rate: 'Tasa de Verificación', total_listings: 'listados totales',
    avg_per_property: 'media por propiedad', verified_tenants: 'inquilinos verificados',
    vs_last_month: 'vs mes anterior',
    inquiry_pipeline: 'Pipeline de Solicitudes', tenant_qualification_funnel: 'Embudo de calificación',
    click_property_details: 'Clic para ver detalles',
    property_label: 'Propiedad', rent: 'Alquiler', inquiries_label: 'Solicitudes',
    conversion: 'Conversión', no_properties: 'Sin propiedades aún',
    qualification_trends: 'Tendencias de Calificación',
    monthly_qualification_metrics: 'Métricas mensuales de calificación',
    screened_label: 'Revisado',
    tenant_label: 'Inquilino', contact: 'Contacto', income: 'Ingresos',
    score: 'Puntuación', status_label: 'Estado', date_label: 'Fecha',
    excellent: 'Excelente', good: 'Bueno', needs_review: 'Necesita Revisión',
    not_connected: 'No conectado', connected_label: 'Conectado',
    employment_verification: 'Verificación de empleo',
    employment_status_label: 'Estado Laboral', company_label: 'Empresa',
    business_email_label: 'Email Empresarial', monthly_income_label: 'Ingreso Mensual',
    income_ratio_label: 'Ratio de Ingresos', credit_score_label: 'Puntuación Crediticia',
    occupants_label: 'Ocupantes', pets_label: 'Mascotas',
    connect_bank_desc: 'Conectar cuenta bancaria para verificar ingresos automáticamente',
    bank_verified: 'Estado: Verificado ✓', bank_pending: 'Verificación pendiente',
    cv_resume: 'CV / Currículum', payslips_label: 'Nóminas',
    work_contract: 'Contrato de Trabajo', id_document: 'Documento de Identidad',
    uploaded: '✓ Cargado', credit_verification: 'Verificación Crediticia',
    db_assessment: 'Evaluación de Dun & Bradstreet',
    step1_label: 'Contacto Inicial', step1_desc: 'Primera solicitud recibida',
    step2_label: 'Carga de Documentos', step2_desc: 'Documentos enviados',
    step3_label: 'Verificación de Identidad', step3_desc: 'Identidad confirmada',
    step4_label: 'Verificación Financiera', step4_desc: 'Ingresos y crédito verificados',
    step5_label: 'Revisión Final', step5_desc: 'Listo para decisión',
    healthy: 'Saludable', high_ratio: 'Alto', target_ratio: 'Objetivo: <40%',
    financing_recommended: 'financiación recomendada al inquilino', clear_label: 'Limpiar',
    tenant_qualified_label: 'Inquilino Calificado',
    klarna_desc1: 'Compra ahora, paga después', klarna_desc2: 'Cuotas flexibles',
    santander_desc1: 'Financiación personal', santander_desc2: 'Tasas competitivas',
    place_of_birth_label: 'Lugar de Nacimiento', dni_nie_label: 'Número DNI/NIE',
    postal_code_label: 'Código Postal', country_label: 'País',
    gdpr_label: 'RGPD Verificado', verified_status: 'Verificado',
    responsible_agent: 'Agente Inmobiliario Responsable',
    name_label: 'Nombre', agency_label: 'Agencia', mobile_label: 'Móvil',
    email_label: 'Correo', approved_rented: 'Aprobado / Alquilado',
    property_status_label: 'Estado',
    rental_contracts: 'Contratos de Alquiler',
    contracts_subtitle: 'Crear, gestionar y enviar contratos de alquiler para firmar',
    create_new_contract: 'Crear Nuevo Contrato',
    select_tenant: 'Seleccionar Inquilino',
    lease_start_date: 'Fecha de Inicio del Arrendamiento',
    lease_end_date: 'Fecha de Fin del Arrendamiento',
    security_deposit: 'Depósito de Seguridad (€)',
    contract_terms: 'Términos y Condiciones del Contrato',
    customize_template: 'Puede personalizar la plantilla o usar los términos predeterminados.',
    create_contract: 'Crear Contrato',
    creating_contract: 'Creando...',
    cancel: 'Cancelar',
    lease_period: 'Período de Arrendamiento',
    tenant_signature_label: 'Firma del Inquilino',
    landlord_signature_label: 'Firma del Propietario',
    send_for_signature: 'Enviar para Firma',
    sending: 'Enviando...',
    awaiting_your_signature: 'Esperando su Firma',
    sign_rental_contract: 'Firmar Contrato de Alquiler',
    sign_contract_header: 'Propiedad',
    contract_terms_label: 'Términos del Contrato',
    your_signature: 'Su Firma',
    type_full_name: 'Escriba su Nombre Completo',
    enter_full_name: 'Ingrese su nombre completo',
    your_signature_preview: 'Su firma aparece aquí',
    sign_contract_btn: 'Firmar Contrato',
    signing_contract: 'Firmando...',
    contract_signed_success: '¡Contrato Firmado Exitosamente!',
    tenant_will_sign_next: 'El propietario ahora deberá revisar y firmar el contrato.',
    both_parties_signed: 'Ambas partes han firmado el contrato. Es legalmente vinculante.',
    contract_not_found: 'Contrato no encontrado. Por favor verifique su enlace de firma.',
    signature_status: 'Estado de Firma',
    tenant: 'Inquilino',
    landlord: 'Propietario',
    already_signed: 'Ya Firmado',
    you_have_signed: 'Ya ha firmado este contrato. Esperando a la otra parte para completar.',
    },
    pt: {
    my_account: 'Minha Conta', edit_profile: 'Editar Perfil', settings: 'Configurações',
    logout: 'Sair', login: 'Entrar',
    my_properties: 'Minhas Propriedades', recent_inquiries: 'Consultas Recentes',
    status_new: 'Novo', status_screening: 'Triagem', status_kyc_pending: 'KYC Pendente',
    status_qualified: 'Qualificado', status_rejected: 'Rejeitado', status_rented: 'Alugado',
    tenant_profile: 'Perfil do Inquilino', landlord_decision: 'Decisão do Proprietário',
    review_approve_desc: 'Rever e aprovar/rejeitar esta candidatura',
    application_progress: 'Progresso da Candidatura', personal_information: 'Informação Pessoal',
    id_verification: 'Verificação de Identidade', connected_profiles: 'Perfis Conectados',
    employment_information: 'Informação de Emprego', financial_information: 'Informação Financeira',
    income_verification: 'Verificação de Rendimento', required_documents: 'Documentos Necessários',
    credit_check: 'Verificação de Crédito', financing_options: 'Opções de Financiamento',
    internal_notes: 'Notas Internas', save_notes: 'Guardar Notas',
    approve: 'Aprovar', reject: 'Rejeitar', pending: 'Pendente',
    property_information: 'Informação da Propriedade', performance_metrics: 'Métricas de Desempenho',
    rental_funnel: 'Funil de Arrendamento',
    view_document: 'Ver Documento', upload: 'Carregar', uploading: 'A carregar...',
    no_inquiries: 'Sem consultas ainda', connect_bank: 'Conectar Conta Bancária',
    bank_connected: 'Conta Bancária Conectada',
    funnel_inquiry: 'Consulta Recebida', funnel_verification: 'Verificação em Curso',
    funnel_qualified: 'Qualificado', funnel_approved: 'Aprovado', funnel_rejected: 'Rejeitado',
    modero_score: 'Pontuação de Qualificação Modero', overall_rating: 'Classificação geral do inquilino',
    add_notes_placeholder: 'Adicionar notas internas sobre este inquilino...',
    notes_saved: 'Notas guardadas com sucesso',
    in_screening: 'Em Triagem', conversion_rate: 'Taxa de Conversão',
    address: 'Endereço', city: 'Cidade', monthly_rent: 'Renda Mensal', bedrooms: 'Quartos',
    idealista_id: 'ID Idealista', total_inquiries: 'Total de Consultas',
    filter_by_status: 'Filtrar por estado', all_inquiries: 'Todas as Consultas',
    active_properties: 'Propriedades Ativas', qualified_tenants_label: 'Inquilinos Qualificados',
    verification_rate: 'Taxa de Verificação', total_listings: 'listagens totais',
    avg_per_property: 'média por propriedade', verified_tenants: 'inquilinos verificados',
    vs_last_month: 'vs mês anterior',
    inquiry_pipeline: 'Pipeline de Consultas', tenant_qualification_funnel: 'Funil de qualificação',
    click_property_details: 'Clique para ver detalhes',
    property_label: 'Propriedade', rent: 'Renda', inquiries_label: 'Consultas',
    conversion: 'Conversão', no_properties: 'Sem propriedades ainda',
    qualification_trends: 'Tendências de Qualificação',
    monthly_qualification_metrics: 'Métricas mensais de qualificação',
    screened_label: 'Triado',
    tenant_label: 'Inquilino', contact: 'Contato', income: 'Rendimento',
    score: 'Pontuação', status_label: 'Estado', date_label: 'Data',
    excellent: 'Excelente', good: 'Bom', needs_review: 'Necessita Revisão',
    not_connected: 'Não conectado', connected_label: 'Conectado',
    employment_verification: 'Verificação de emprego',
    employment_status_label: 'Estado de Emprego', company_label: 'Empresa',
    business_email_label: 'Email Empresarial', monthly_income_label: 'Rendimento Mensal',
    income_ratio_label: 'Rácio de Rendimento', credit_score_label: 'Pontuação de Crédito',
    occupants_label: 'Ocupantes', pets_label: 'Animais de Estimação',
    connect_bank_desc: 'Conectar conta bancária para verificar rendimento automaticamente',
    bank_verified: 'Estado: Verificado ✓', bank_pending: 'Verificação pendente',
    cv_resume: 'CV / Currículo', payslips_label: 'Recibos de Salário',
    work_contract: 'Contrato de Trabalho', id_document: 'Documento de Identidade',
    uploaded: '✓ Enviado', credit_verification: 'Verificação de Crédito',
    db_assessment: 'Avaliação Dun & Bradstreet',
    step1_label: 'Contato Inicial', step1_desc: 'Primeira consulta recebida',
    step2_label: 'Envio de Documentos', step2_desc: 'Documentos enviados',
    step3_label: 'Verificação de Identidade', step3_desc: 'Identidade confirmada',
    step4_label: 'Verificação Financeira', step4_desc: 'Rendimento e crédito verificados',
    step5_label: 'Revisão Final', step5_desc: 'Pronto para decisão',
    healthy: 'Saudável', high_ratio: 'Alto', target_ratio: 'Objetivo: <40%',
    financing_recommended: 'financiamento recomendado ao inquilino', clear_label: 'Limpar',
    tenant_qualified_label: 'Inquilino Qualificado',
    klarna_desc1: 'Compra agora, paga depois', klarna_desc2: 'Prestações flexíveis',
    santander_desc1: 'Financiamento pessoal', santander_desc2: 'Taxas competitivas',
    place_of_birth_label: 'Local de Nascimento', dni_nie_label: 'Número DNI/NIE',
    postal_code_label: 'Código Postal', country_label: 'País',
    gdpr_label: 'RGPD Verificado', verified_status: 'Verificado',
    responsible_agent: 'Agente Imobiliário Responsável',
    name_label: 'Nome', agency_label: 'Agência', mobile_label: 'Telemóvel',
    email_label: 'Email', approved_rented: 'Aprovado / Alugado',
    property_status_label: 'Estado',
    rental_contracts: 'Contratos de Arrendamento',
    contracts_subtitle: 'Criar, gerir e enviar contratos de arrendamento para assinatura',
    create_new_contract: 'Criar Novo Contrato',
    select_tenant: 'Selecionar Inquilino',
    lease_start_date: 'Data de Início do Arrendamento',
    lease_end_date: 'Data de Fim do Arrendamento',
    security_deposit: 'Depósito de Caução (€)',
    contract_terms: 'Termos e Condições do Contrato',
    customize_template: 'Pode personalizar o modelo ou utilizar os termos predefinidos.',
    create_contract: 'Criar Contrato',
    creating_contract: 'A criar...',
    cancel: 'Cancelar',
    lease_period: 'Período de Arrendamento',
    tenant_signature_label: 'Assinatura do Inquilino',
    landlord_signature_label: 'Assinatura do Proprietário',
    send_for_signature: 'Enviar para Assinatura',
    sending: 'A enviar...',
    awaiting_your_signature: 'Aguardando a sua Assinatura',
    sign_rental_contract: 'Assinar Contrato de Arrendamento',
    sign_contract_header: 'Propriedade',
    contract_terms_label: 'Termos do Contrato',
    your_signature: 'Sua Assinatura',
    type_full_name: 'Digite seu Nome Completo',
    enter_full_name: 'Introduza o seu nome completo',
    your_signature_preview: 'A sua assinatura aparece aqui',
    sign_contract_btn: 'Assinar Contrato',
    signing_contract: 'A assinar...',
    contract_signed_success: 'Contrato Assinado com Sucesso!',
    tenant_will_sign_next: 'O proprietário agora necessita rever e assinar o contrato.',
    both_parties_signed: 'Ambas as partes assinaram o contrato. É legalmente vinculativo.',
    contract_not_found: 'Contrato não encontrado. Verifique o seu link de assinatura.',
    signature_status: 'Estado de Assinatura',
    tenant: 'Inquilino',
    landlord: 'Proprietário',
    already_signed: 'Já Assinado',
    you_have_signed: 'Já assinou este contrato. Aguardando a outra parte para completar.',
    },
    it: {
    my_account: 'Il Mio Account', edit_profile: 'Modifica Profilo', settings: 'Impostazioni',
    logout: 'Disconnetti', login: 'Accedi',
    my_properties: 'Le Mie Proprietà', recent_inquiries: 'Richieste Recenti',
    status_new: 'Nuovo', status_screening: 'Screening', status_kyc_pending: 'KYC in Attesa',
    status_qualified: 'Qualificato', status_rejected: 'Rifiutato', status_rented: 'Affittato',
    tenant_profile: 'Profilo Inquilino', landlord_decision: 'Decisione Proprietario',
    review_approve_desc: 'Rivedi e approva/rifiuta questa candidatura',
    application_progress: 'Avanzamento Candidatura', personal_information: 'Informazioni Personali',
    id_verification: 'Verifica Identità', connected_profiles: 'Profili Collegati',
    employment_information: 'Informazioni Lavorative', financial_information: 'Informazioni Finanziarie',
    income_verification: 'Verifica Reddito', required_documents: 'Documenti Richiesti',
    credit_check: 'Controllo Credito', financing_options: 'Opzioni di Finanziamento',
    internal_notes: 'Note Interne', save_notes: 'Salva Note',
    approve: 'Approva', reject: 'Rifiuta', pending: 'In Attesa',
    property_information: 'Informazioni Proprietà', performance_metrics: 'Metriche di Performance',
    rental_funnel: 'Funnel di Locazione',
    view_document: 'Visualizza Documento', upload: 'Carica', uploading: 'Caricamento...',
    no_inquiries: 'Nessuna richiesta', connect_bank: 'Collega Conto Bancario',
    bank_connected: 'Conto Bancario Collegato',
    funnel_inquiry: 'Richiesta Ricevuta', funnel_verification: 'Verifica in Corso',
    funnel_qualified: 'Qualificato', funnel_approved: 'Approvato', funnel_rejected: 'Rifiutato',
    modero_score: 'Punteggio Qualificazione Modero', overall_rating: 'Valutazione complessiva inquilino',
    add_notes_placeholder: 'Aggiungi note interne su questo inquilino...',
    notes_saved: 'Note salvate con successo',
    in_screening: 'In Screening', conversion_rate: 'Tasso di Conversione',
    address: 'Indirizzo', city: 'Città', monthly_rent: 'Affitto Mensile', bedrooms: 'Camere',
    idealista_id: 'ID Idealista', total_inquiries: 'Totale Richieste',
    filter_by_status: 'Filtra per stato', all_inquiries: 'Tutte le Richieste',
    active_properties: 'Proprietà Attive', qualified_tenants_label: 'Inquilini Qualificati',
    verification_rate: 'Tasso di Verifica', total_listings: 'annunci totali',
    avg_per_property: 'media per proprietà', verified_tenants: 'inquilini verificati',
    vs_last_month: 'vs mese scorso',
    inquiry_pipeline: 'Pipeline Richieste', tenant_qualification_funnel: 'Funnel di qualificazione',
    click_property_details: 'Clicca per i dettagli',
    property_label: 'Proprietà', rent: 'Affitto', inquiries_label: 'Richieste',
    conversion: 'Conversione', no_properties: 'Nessuna proprietà',
    qualification_trends: 'Tendenze di Qualificazione',
    monthly_qualification_metrics: 'Metriche mensili di qualificazione',
    screened_label: 'Esaminato',
    tenant_label: 'Inquilino', contact: 'Contatto', income: 'Reddito',
    score: 'Punteggio', status_label: 'Stato', date_label: 'Data',
    excellent: 'Eccellente', good: 'Buono', needs_review: 'Necessita Revisione',
    not_connected: 'Non collegato', connected_label: 'Collegato',
    employment_verification: 'Verifica impiego',
    employment_status_label: 'Stato Lavorativo', company_label: 'Azienda',
    business_email_label: 'Email Aziendale', monthly_income_label: 'Reddito Mensile',
    income_ratio_label: 'Rapporto Reddito', credit_score_label: 'Punteggio di Credito',
    occupants_label: 'Occupanti', pets_label: 'Animali',
    connect_bank_desc: 'Collega conto bancario per verificare il reddito mensile automaticamente',
    bank_verified: 'Stato: Verificato ✓', bank_pending: 'Verifica in attesa',
    cv_resume: 'CV / Curriculum', payslips_label: 'Buste Paga',
    work_contract: 'Contratto di Lavoro', id_document: "Documento d'Identità",
    uploaded: '✓ Caricato', credit_verification: 'Verifica Credito',
    db_assessment: 'Valutazione Dun & Bradstreet',
    step1_label: 'Contatto Iniziale', step1_desc: 'Prima richiesta ricevuta',
    step2_label: 'Caricamento Documenti', step2_desc: 'Documenti inviati',
    step3_label: 'Verifica Identità', step3_desc: 'Identità confermata',
    step4_label: 'Verifica Finanziaria', step4_desc: 'Reddito e credito verificati',
    step5_label: 'Revisione Finale', step5_desc: 'Pronto per la decisione',
    healthy: 'Sano', high_ratio: 'Alto', target_ratio: 'Obiettivo: <40%',
    financing_recommended: "finanziamento raccomandato all'inquilino", clear_label: 'Cancella',
    tenant_qualified_label: 'Inquilino Qualificato',
    klarna_desc1: 'Compra ora, paga dopo', klarna_desc2: 'Rate flessibili',
    santander_desc1: 'Finanziamento personale', santander_desc2: 'Tassi competitivi',
    place_of_birth_label: 'Luogo di Nascita', dni_nie_label: 'Numero DNI/NIE',
    postal_code_label: 'Codice Postale', country_label: 'Paese',
    gdpr_label: 'GDPR Verificato', verified_status: 'Verificato',
    responsible_agent: 'Agente Immobiliare Responsabile',
    name_label: 'Nome', agency_label: 'Agenzia', mobile_label: 'Cellulare',
    email_label: 'Email', approved_rented: 'Approvato / Affittato',
    property_status_label: 'Stato',
    rental_contracts: 'Contratti di Locazione',
    contracts_subtitle: 'Crea, gestisci e invia contratti di locazione per la firma',
    create_new_contract: 'Crea Nuovo Contratto',
    select_tenant: 'Seleziona Inquilino',
    lease_start_date: 'Data Inizio Locazione',
    lease_end_date: 'Data Fine Locazione',
    security_deposit: 'Cauzione (€)',
    contract_terms: 'Termini e Condizioni del Contratto',
    customize_template: 'Puoi personalizzare il modello o utilizzare i termini predefiniti.',
    create_contract: 'Crea Contratto',
    creating_contract: 'Creazione...',
    cancel: 'Annulla',
    lease_period: 'Periodo di Locazione',
    tenant_signature_label: 'Firma Inquilino',
    landlord_signature_label: 'Firma Proprietario',
    send_for_signature: 'Invia per la Firma',
    sending: 'Invio in corso...',
    awaiting_your_signature: 'In Attesa della Tua Firma',
    sign_rental_contract: 'Firma Contratto di Locazione',
    sign_contract_header: 'Proprietà',
    contract_terms_label: 'Termini del Contratto',
    your_signature: 'Tua Firma',
    type_full_name: 'Digita il Tuo Nome Completo',
    enter_full_name: 'Inserisci il tuo nome completo',
    your_signature_preview: 'La tua firma appare qui',
    sign_contract_btn: 'Firma Contratto',
    signing_contract: 'Firma in corso...',
    contract_signed_success: 'Contratto Firmato con Successo!',
    tenant_will_sign_next: 'Il proprietario ora deve revisionare e firmare il contratto.',
    both_parties_signed: 'Entrambe le parti hanno firmato il contratto. È legalmente vincolante.',
    contract_not_found: 'Contratto non trovato. Verifica il tuo link di firma.',
    signature_status: 'Stato Firma',
    tenant: 'Inquilino',
    landlord: 'Proprietario',
    already_signed: 'Già Firmato',
    you_have_signed: 'Hai già firmato questo contratto. In attesa dell\'altra parte per completare.',
    },
    };

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');
  const t = (key) => translations[language]?.[key] ?? translations.en[key] ?? key;
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}