import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // Auth/Header
    my_account: 'My Account', edit_profile: 'Edit Profile', settings: 'Settings',
    logout: 'Logout', login: 'Login',
    // Dashboard filters
    filter_by_status: 'Filter by status', all_inquiries: 'All Inquiries',
    active_properties: 'Active Properties', total_inquiries: 'Total Inquiries',
    qualified_tenants: 'Qualified Tenants', verification_rate: 'Verification Rate',
    total_listings: 'total listings', avg_per_property: 'avg per property',
    verified_tenants: 'verified tenants', vs_last_month: 'vs last month',
    conversion_rate: 'conversion rate',
    // Statuses
    status_new: 'New', status_screening: 'Screening', status_kyc_pending: 'KYC Pending',
    status_qualified: 'Qualified', status_rejected: 'Rejected', status_rented: 'Rented',
    // Recent Inquiries table
    recent_inquiries: 'Recent Inquiries', tenant: 'Tenant', contact: 'Contact',
    income: 'Income', score: 'Score', status_label: 'Status', date: 'Date',
    no_inquiries: 'No inquiries yet', idealista_id: 'Idealista ID',
    // Property Performance
    my_properties: 'My Properties', click_property_details: 'Click a property to view details',
    property: 'Property', rent: 'Rent', inquiries: 'Inquiries',
    qualified: 'Qualified', conversion: 'Conversion', no_properties: 'No properties yet',
    // Inquiry Funnel
    inquiry_pipeline: 'Inquiry Pipeline', tenant_qual_funnel: 'Tenant qualification funnel',
    // Trends Chart
    qualification_trends: 'Qualification Trends',
    monthly_qual_metrics: 'Monthly tenant qualification metrics', screened: 'Screened',
    // Tenant Dialog
    tenant_profile: 'Tenant Profile',
    modero_score: 'Modero Qualification Score',
    overall_rating: 'Overall tenant qualification rating',
    excellent: 'Excellent', good: 'Good', needs_review: 'Needs Review',
    landlord_decision: 'Landlord Decision',
    review_approve_desc: 'Review and approve/reject this application',
    approve: 'Approve', reject: 'Reject', pending: 'Pending',
    application_progress: 'Application Progress', step: 'Step',
    step1_label: 'Initial Contact', step1_desc: 'First inquiry received',
    step2_label: 'Document Upload', step2_desc: 'Documents submitted',
    step3_label: 'ID Verification', step3_desc: 'Identity confirmed',
    step4_label: 'Financial Check', step4_desc: 'Income & credit verified',
    step5_label: 'Final Review', step5_desc: 'Ready for decision',
    personal_information: 'Personal Information',
    email_label: 'Email', phone_label: 'Phone',
    address: 'Address', postal_code: 'Postal Code', city: 'City', country: 'Country',
    place_of_birth: 'Place of Birth', dni_nie: 'DNI/NIE Number',
    gdpr_verified: 'GDPR Verified', verified: 'Verified', not_verified: 'Not verified',
    connected_profiles: 'Connected Profiles', not_connected: 'Not connected',
    employment_verification: 'Employment verification',
    employment_information: 'Employment Information',
    employment_status: 'Employment Status', company: 'Company', business_email: 'Business Email',
    financial_information: 'Financial Information',
    monthly_income: 'Monthly Income', income_ratio: 'Income Ratio',
    credit_score_label: 'Credit Score', occupants: 'Occupants', pets: 'Pets',
    income_verification: 'Income Verification',
    connect_bank_desc: 'Connect bank account to automatically verify monthly income',
    bank_connected: 'Bank Account Connected', connect_bank: 'Connect Bank Account',
    required_documents: 'Required Documents',
    view_document: 'View Document', upload: 'Upload', uploading: 'Uploading...', uploaded: 'Uploaded',
    cv_resume: 'CV / Resume', payslips: 'Payslips', work_contract: 'Work Contract', id_document: 'ID Document',
    credit_check: 'Credit Check', credit_verification: 'Credit Verification',
    dnb_assessment: 'Dun & Bradstreet assessment',
    financing_options: 'Financing Options', tenant_qualified: 'Tenant Qualified',
    recommend_financing: 'Recommend a financing solution to this tenant',
    financing_recommended: 'financing recommended to tenant', clear: 'Clear',
    internal_notes: 'Internal Notes', save_notes: 'Save Notes',
    add_notes_placeholder: 'Add internal notes about this tenant...', notes_saved: 'Notes saved',
    // Property Dialog
    property_information: 'Property Information', monthly_rent: 'Monthly Rent', bedrooms: 'Bedrooms',
    performance_metrics: 'Performance Metrics', in_screening: 'In Screening',
    approved_rented: 'Approved / Rented', rental_funnel: 'Rental Funnel',
    funnel_inquiry: 'Inquiry Received', funnel_verification: 'Verification in Progress',
    funnel_qualified: 'Qualified', funnel_approved: 'Approved', funnel_rejected: 'Rejected',
    responsible_agent: 'Responsible Real Estate Agent',
    name: 'Name', agency: 'Agency', mobile: 'Mobile',
  },
  es: {
    my_account: 'Mi Cuenta', edit_profile: 'Editar Perfil', settings: 'Configuración',
    logout: 'Cerrar Sesión', login: 'Iniciar Sesión',
    filter_by_status: 'Filtrar por estado', all_inquiries: 'Todas las Solicitudes',
    active_properties: 'Propiedades Activas', total_inquiries: 'Total Solicitudes',
    qualified_tenants: 'Inquilinos Calificados', verification_rate: 'Tasa de Verificación',
    total_listings: 'listados totales', avg_per_property: 'promedio por propiedad',
    verified_tenants: 'inquilinos verificados', vs_last_month: 'vs mes anterior',
    conversion_rate: 'tasa de conversión',
    status_new: 'Nuevo', status_screening: 'En Revisión', status_kyc_pending: 'KYC Pendiente',
    status_qualified: 'Calificado', status_rejected: 'Rechazado', status_rented: 'Alquilado',
    recent_inquiries: 'Solicitudes Recientes', tenant: 'Inquilino', contact: 'Contacto',
    income: 'Ingresos', score: 'Puntuación', status_label: 'Estado', date: 'Fecha',
    no_inquiries: 'Sin solicitudes aún', idealista_id: 'ID Idealista',
    my_properties: 'Mis Propiedades', click_property_details: 'Haz clic en una propiedad para ver detalles',
    property: 'Propiedad', rent: 'Alquiler', inquiries: 'Solicitudes',
    qualified: 'Calificado', conversion: 'Conversión', no_properties: 'Sin propiedades aún',
    inquiry_pipeline: 'Pipeline de Solicitudes', tenant_qual_funnel: 'Embudo de calificación de inquilinos',
    qualification_trends: 'Tendencias de Calificación',
    monthly_qual_metrics: 'Métricas mensuales de calificación de inquilinos', screened: 'Revisados',
    tenant_profile: 'Perfil del Inquilino',
    modero_score: 'Puntuación de Calificación Modero',
    overall_rating: 'Calificación general del inquilino',
    excellent: 'Excelente', good: 'Bueno', needs_review: 'Necesita Revisión',
    landlord_decision: 'Decisión del Propietario',
    review_approve_desc: 'Revisar y aprobar/rechazar esta solicitud',
    approve: 'Aprobar', reject: 'Rechazar', pending: 'Pendiente',
    application_progress: 'Progreso de Solicitud', step: 'Paso',
    step1_label: 'Contacto Inicial', step1_desc: 'Primera solicitud recibida',
    step2_label: 'Subida de Documentos', step2_desc: 'Documentos enviados',
    step3_label: 'Verificación de ID', step3_desc: 'Identidad confirmada',
    step4_label: 'Verificación Financiera', step4_desc: 'Ingresos y crédito verificados',
    step5_label: 'Revisión Final', step5_desc: 'Listo para decisión',
    personal_information: 'Información Personal',
    email_label: 'Correo', phone_label: 'Teléfono',
    address: 'Dirección', postal_code: 'Código Postal', city: 'Ciudad', country: 'País',
    place_of_birth: 'Lugar de Nacimiento', dni_nie: 'Número DNI/NIE',
    gdpr_verified: 'GDPR Verificado', verified: 'Verificado', not_verified: 'No verificado',
    connected_profiles: 'Perfiles Conectados', not_connected: 'No conectado',
    employment_verification: 'Verificación de empleo',
    employment_information: 'Información Laboral',
    employment_status: 'Estado Laboral', company: 'Empresa', business_email: 'Correo Empresarial',
    financial_information: 'Información Financiera',
    monthly_income: 'Ingresos Mensuales', income_ratio: 'Ratio de Ingresos',
    credit_score_label: 'Puntuación Crediticia', occupants: 'Ocupantes', pets: 'Mascotas',
    income_verification: 'Verificación de Ingresos',
    connect_bank_desc: 'Conectar cuenta bancaria para verificar ingresos mensuales automáticamente',
    bank_connected: 'Cuenta Bancaria Conectada', connect_bank: 'Conectar Cuenta Bancaria',
    required_documents: 'Documentos Requeridos',
    view_document: 'Ver Documento', upload: 'Subir', uploading: 'Subiendo...', uploaded: 'Subido',
    cv_resume: 'CV / Currículum', payslips: 'Nóminas', work_contract: 'Contrato de Trabajo', id_document: 'Documento de Identidad',
    credit_check: 'Verificación Crediticia', credit_verification: 'Verificación Crediticia',
    dnb_assessment: 'Evaluación Dun & Bradstreet',
    financing_options: 'Opciones de Financiación', tenant_qualified: 'Inquilino Calificado',
    recommend_financing: 'Recomendar una solución de financiación a este inquilino',
    financing_recommended: 'financiación recomendada al inquilino', clear: 'Limpiar',
    internal_notes: 'Notas Internas', save_notes: 'Guardar Notas',
    add_notes_placeholder: 'Agregar notas internas sobre este inquilino...', notes_saved: 'Notas guardadas correctamente',
    property_information: 'Información de Propiedad', monthly_rent: 'Renta Mensual', bedrooms: 'Habitaciones',
    performance_metrics: 'Métricas de Rendimiento', in_screening: 'En Revisión',
    approved_rented: 'Aprobado / Alquilado', rental_funnel: 'Embudo de Alquiler',
    funnel_inquiry: 'Solicitud Recibida', funnel_verification: 'Verificación en Curso',
    funnel_qualified: 'Calificado', funnel_approved: 'Aprobado', funnel_rejected: 'Rechazado',
    responsible_agent: 'Agente Inmobiliario Responsable',
    name: 'Nombre', agency: 'Agencia', mobile: 'Móvil',
  },
  pt: {
    my_account: 'Minha Conta', edit_profile: 'Editar Perfil', settings: 'Configurações',
    logout: 'Sair', login: 'Entrar',
    filter_by_status: 'Filtrar por estado', all_inquiries: 'Todas as Consultas',
    active_properties: 'Propriedades Ativas', total_inquiries: 'Total Consultas',
    qualified_tenants: 'Inquilinos Qualificados', verification_rate: 'Taxa de Verificação',
    total_listings: 'total de listagens', avg_per_property: 'média por propriedade',
    verified_tenants: 'inquilinos verificados', vs_last_month: 'vs mês anterior',
    conversion_rate: 'taxa de conversão',
    status_new: 'Novo', status_screening: 'Triagem', status_kyc_pending: 'KYC Pendente',
    status_qualified: 'Qualificado', status_rejected: 'Rejeitado', status_rented: 'Alugado',
    recent_inquiries: 'Consultas Recentes', tenant: 'Inquilino', contact: 'Contacto',
    income: 'Rendimento', score: 'Pontuação', status_label: 'Estado', date: 'Data',
    no_inquiries: 'Sem consultas ainda', idealista_id: 'ID Idealista',
    my_properties: 'Minhas Propriedades', click_property_details: 'Clique numa propriedade para ver detalhes',
    property: 'Propriedade', rent: 'Renda', inquiries: 'Consultas',
    qualified: 'Qualificado', conversion: 'Conversão', no_properties: 'Sem propriedades ainda',
    inquiry_pipeline: 'Pipeline de Consultas', tenant_qual_funnel: 'Funil de qualificação de inquilinos',
    qualification_trends: 'Tendências de Qualificação',
    monthly_qual_metrics: 'Métricas mensais de qualificação de inquilinos', screened: 'Triados',
    tenant_profile: 'Perfil do Inquilino',
    modero_score: 'Pontuação de Qualificação Modero',
    overall_rating: 'Classificação geral do inquilino',
    excellent: 'Excelente', good: 'Bom', needs_review: 'Precisa de Revisão',
    landlord_decision: 'Decisão do Proprietário',
    review_approve_desc: 'Rever e aprovar/rejeitar esta candidatura',
    approve: 'Aprovar', reject: 'Rejeitar', pending: 'Pendente',
    application_progress: 'Progresso da Candidatura', step: 'Passo',
    step1_label: 'Contacto Inicial', step1_desc: 'Primeira consulta recebida',
    step2_label: 'Upload de Documentos', step2_desc: 'Documentos enviados',
    step3_label: 'Verificação de ID', step3_desc: 'Identidade confirmada',
    step4_label: 'Verificação Financeira', step4_desc: 'Rendimento e crédito verificados',
    step5_label: 'Revisão Final', step5_desc: 'Pronto para decisão',
    personal_information: 'Informação Pessoal',
    email_label: 'Email', phone_label: 'Telefone',
    address: 'Endereço', postal_code: 'Código Postal', city: 'Cidade', country: 'País',
    place_of_birth: 'Local de Nascimento', dni_nie: 'Número DNI/NIE',
    gdpr_verified: 'GDPR Verificado', verified: 'Verificado', not_verified: 'Não verificado',
    connected_profiles: 'Perfis Conectados', not_connected: 'Não conectado',
    employment_verification: 'Verificação de emprego',
    employment_information: 'Informação de Emprego',
    employment_status: 'Estado de Emprego', company: 'Empresa', business_email: 'Email Empresarial',
    financial_information: 'Informação Financeira',
    monthly_income: 'Rendimento Mensal', income_ratio: 'Rácio de Rendimento',
    credit_score_label: 'Pontuação de Crédito', occupants: 'Ocupantes', pets: 'Animais',
    income_verification: 'Verificação de Rendimento',
    connect_bank_desc: 'Conectar conta bancária para verificar automaticamente o rendimento mensal',
    bank_connected: 'Conta Bancária Conectada', connect_bank: 'Conectar Conta Bancária',
    required_documents: 'Documentos Necessários',
    view_document: 'Ver Documento', upload: 'Carregar', uploading: 'A carregar...', uploaded: 'Carregado',
    cv_resume: 'CV / Currículo', payslips: 'Recibos de Vencimento', work_contract: 'Contrato de Trabalho', id_document: 'Documento de Identidade',
    credit_check: 'Verificação de Crédito', credit_verification: 'Verificação de Crédito',
    dnb_assessment: 'Avaliação Dun & Bradstreet',
    financing_options: 'Opções de Financiamento', tenant_qualified: 'Inquilino Qualificado',
    recommend_financing: 'Recomendar uma solução de financiamento a este inquilino',
    financing_recommended: 'financiamento recomendado ao inquilino', clear: 'Limpar',
    internal_notes: 'Notas Internas', save_notes: 'Guardar Notas',
    add_notes_placeholder: 'Adicionar notas internas sobre este inquilino...', notes_saved: 'Notas guardadas com sucesso',
    property_information: 'Informação da Propriedade', monthly_rent: 'Renda Mensal', bedrooms: 'Quartos',
    performance_metrics: 'Métricas de Desempenho', in_screening: 'Em Triagem',
    approved_rented: 'Aprovado / Alugado', rental_funnel: 'Funil de Arrendamento',
    funnel_inquiry: 'Consulta Recebida', funnel_verification: 'Verificação em Curso',
    funnel_qualified: 'Qualificado', funnel_approved: 'Aprovado', funnel_rejected: 'Rejeitado',
    responsible_agent: 'Agente Imobiliário Responsável',
    name: 'Nome', agency: 'Agência', mobile: 'Telemóvel',
  },
  it: {
    my_account: 'Il Mio Account', edit_profile: 'Modifica Profilo', settings: 'Impostazioni',
    logout: 'Disconnetti', login: 'Accedi',
    filter_by_status: 'Filtra per stato', all_inquiries: 'Tutte le Richieste',
    active_properties: 'Proprietà Attive', total_inquiries: 'Totale Richieste',
    qualified_tenants: 'Inquilini Qualificati', verification_rate: 'Tasso di Verifica',
    total_listings: 'totale annunci', avg_per_property: 'media per proprietà',
    verified_tenants: 'inquilini verificati', vs_last_month: 'vs mese scorso',
    conversion_rate: 'tasso di conversione',
    status_new: 'Nuovo', status_screening: 'Screening', status_kyc_pending: 'KYC in Attesa',
    status_qualified: 'Qualificato', status_rejected: 'Rifiutato', status_rented: 'Affittato',
    recent_inquiries: 'Richieste Recenti', tenant: 'Inquilino', contact: 'Contatto',
    income: 'Reddito', score: 'Punteggio', status_label: 'Stato', date: 'Data',
    no_inquiries: 'Nessuna richiesta', idealista_id: 'ID Idealista',
    my_properties: 'Le Mie Proprietà', click_property_details: 'Clicca su una proprietà per vedere i dettagli',
    property: 'Proprietà', rent: 'Affitto', inquiries: 'Richieste',
    qualified: 'Qualificato', conversion: 'Conversione', no_properties: 'Nessuna proprietà ancora',
    inquiry_pipeline: 'Pipeline Richieste', tenant_qual_funnel: 'Funnel di qualificazione inquilini',
    qualification_trends: 'Tendenze di Qualificazione',
    monthly_qual_metrics: 'Metriche mensili di qualificazione inquilini', screened: 'Selezionati',
    tenant_profile: 'Profilo Inquilino',
    modero_score: 'Punteggio Qualificazione Modero',
    overall_rating: 'Valutazione complessiva inquilino',
    excellent: 'Eccellente', good: 'Buono', needs_review: 'Da Revisionare',
    landlord_decision: 'Decisione Proprietario',
    review_approve_desc: 'Rivedi e approva/rifiuta questa candidatura',
    approve: 'Approva', reject: 'Rifiuta', pending: 'In Attesa',
    application_progress: 'Avanzamento Candidatura', step: 'Passo',
    step1_label: 'Contatto Iniziale', step1_desc: 'Prima richiesta ricevuta',
    step2_label: 'Caricamento Documenti', step2_desc: 'Documenti inviati',
    step3_label: 'Verifica Identità', step3_desc: 'Identità confermata',
    step4_label: 'Verifica Finanziaria', step4_desc: 'Reddito e credito verificati',
    step5_label: 'Revisione Finale', step5_desc: 'Pronto per la decisione',
    personal_information: 'Informazioni Personali',
    email_label: 'Email', phone_label: 'Telefono',
    address: 'Indirizzo', postal_code: 'Codice Postale', city: 'Città', country: 'Paese',
    place_of_birth: 'Luogo di Nascita', dni_nie: 'Numero DNI/NIE',
    gdpr_verified: 'GDPR Verificato', verified: 'Verificato', not_verified: 'Non verificato',
    connected_profiles: 'Profili Collegati', not_connected: 'Non connesso',
    employment_verification: 'Verifica impiego',
    employment_information: 'Informazioni Lavorative',
    employment_status: 'Stato Lavorativo', company: 'Azienda', business_email: 'Email Aziendale',
    financial_information: 'Informazioni Finanziarie',
    monthly_income: 'Reddito Mensile', income_ratio: 'Rapporto Reddito',
    credit_score_label: 'Punteggio Credito', occupants: 'Occupanti', pets: 'Animali',
    income_verification: 'Verifica Reddito',
    connect_bank_desc: 'Collega il conto bancario per verificare automaticamente il reddito mensile',
    bank_connected: 'Conto Bancario Collegato', connect_bank: 'Collega Conto Bancario',
    required_documents: 'Documenti Richiesti',
    view_document: 'Visualizza Documento', upload: 'Carica', uploading: 'Caricamento...', uploaded: 'Caricato',
    cv_resume: 'CV / Curriculum', payslips: 'Buste Paga', work_contract: 'Contratto di Lavoro', id_document: "Documento d'Identità",
    credit_check: 'Controllo Credito', credit_verification: 'Verifica Credito',
    dnb_assessment: 'Valutazione Dun & Bradstreet',
    financing_options: 'Opzioni di Finanziamento', tenant_qualified: 'Inquilino Qualificato',
    recommend_financing: 'Consiglia una soluzione finanziaria a questo inquilino',
    financing_recommended: "finanziamento consigliato all'inquilino", clear: 'Cancella',
    internal_notes: 'Note Interne', save_notes: 'Salva Note',
    add_notes_placeholder: 'Aggiungi note interne su questo inquilino...', notes_saved: 'Note salvate con successo',
    property_information: 'Informazioni Proprietà', monthly_rent: 'Affitto Mensile', bedrooms: 'Camere',
    performance_metrics: 'Metriche di Performance', in_screening: 'In Screening',
    approved_rented: 'Approvato / Affittato', rental_funnel: 'Funnel di Locazione',
    funnel_inquiry: 'Richiesta Ricevuta', funnel_verification: 'Verifica in Corso',
    funnel_qualified: 'Qualificato', funnel_approved: 'Approvato', funnel_rejected: 'Rifiutato',
    responsible_agent: 'Agente Immobiliare Responsabile',
    name: 'Nome', agency: 'Agenzia', mobile: 'Cellulare',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');
  const t = (key) => translations[language]?.[key] ?? translations.en[key] ?? key;
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}