import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    my_account: 'My Account', edit_profile: 'Edit Profile', settings: 'Settings',
    logout: 'Logout', login: 'Login',
    my_properties: 'My Properties', recent_inquiries: 'Recent Inquiries',
    status_new: 'New', status_screening: 'Screening', status_kyc_pending: 'KYC Pending',
    status_qualified: 'Qualified', status_rejected: 'Rejected', status_rented: 'Rented',
    tenant_profile: 'Tenant Profile', landlord_decision: 'Landlord Decision',
    review_approve_desc: 'Review and approve/reject this application',
    application_progress: 'Application Progress', personal_information: 'Personal Information',
    id_verification: 'ID Verification', connected_profiles: 'Connected Profiles',
    employment_information: 'Employment Information', financial_information: 'Financial Information',
    income_verification: 'Income Verification', required_documents: 'Required Documents',
    credit_check: 'Credit Check', financing_options: 'Financing Options',
    internal_notes: 'Internal Notes', save_notes: 'Save Notes',
    approve: 'Approve', reject: 'Reject', pending: 'Pending',
    property_information: 'Property Information', performance_metrics: 'Performance Metrics',
    rental_funnel: 'Rental Funnel',
    view_document: 'View Document', upload: 'Upload', uploading: 'Uploading...',
    no_inquiries: 'No inquiries yet', connect_bank: 'Connect Bank Account',
    bank_connected: 'Bank Account Connected',
    funnel_inquiry: 'Inquiry Received', funnel_verification: 'Verification in Progress',
    funnel_qualified: 'Qualified', funnel_approved: 'Approved', funnel_rejected: 'Rejected',
    modero_score: 'Modero Qualification Score', overall_rating: 'Overall tenant qualification rating',
    add_notes_placeholder: 'Add internal notes about this tenant...',
    notes_saved: 'Notes saved successfully',
    in_screening: 'In Screening', conversion_rate: 'Conversion Rate',
    address: 'Address', city: 'City', monthly_rent: 'Monthly Rent', bedrooms: 'Bedrooms',
    idealista_id: 'Idealista ID', total_inquiries: 'Total Inquiries',
  },
  es: {
    my_account: 'Mi Cuenta', edit_profile: 'Editar Perfil', settings: 'Configuración',
    logout: 'Cerrar Sesión', login: 'Iniciar Sesión',
    my_properties: 'Mis Propiedades', recent_inquiries: 'Solicitudes Recientes',
    status_new: 'Nuevo', status_screening: 'En Revisión', status_kyc_pending: 'KYC Pendiente',
    status_qualified: 'Calificado', status_rejected: 'Rechazado', status_rented: 'Alquilado',
    tenant_profile: 'Perfil del Inquilino', landlord_decision: 'Decisión del Propietario',
    review_approve_desc: 'Revisar y aprobar/rechazar esta solicitud',
    application_progress: 'Progreso de Solicitud', personal_information: 'Información Personal',
    id_verification: 'Verificación de Identidad', connected_profiles: 'Perfiles Conectados',
    employment_information: 'Información Laboral', financial_information: 'Información Financiera',
    income_verification: 'Verificación de Ingresos', required_documents: 'Documentos Requeridos',
    credit_check: 'Verificación Crediticia', financing_options: 'Opciones de Financiación',
    internal_notes: 'Notas Internas', save_notes: 'Guardar Notas',
    approve: 'Aprobar', reject: 'Rechazar', pending: 'Pendiente',
    property_information: 'Información de Propiedad', performance_metrics: 'Métricas de Rendimiento',
    rental_funnel: 'Embudo de Alquiler',
    view_document: 'Ver Documento', upload: 'Subir', uploading: 'Subiendo...',
    no_inquiries: 'Sin solicitudes aún', connect_bank: 'Conectar Cuenta Bancaria',
    bank_connected: 'Cuenta Bancaria Conectada',
    funnel_inquiry: 'Solicitud Recibida', funnel_verification: 'Verificación en Curso',
    funnel_qualified: 'Calificado', funnel_approved: 'Aprobado', funnel_rejected: 'Rechazado',
    modero_score: 'Puntuación de Calificación Modero', overall_rating: 'Calificación general del inquilino',
    add_notes_placeholder: 'Agregar notas internas sobre este inquilino...',
    notes_saved: 'Notas guardadas correctamente',
    in_screening: 'En Revisión', conversion_rate: 'Tasa de Conversión',
    address: 'Dirección', city: 'Ciudad', monthly_rent: 'Renta Mensual', bedrooms: 'Habitaciones',
    idealista_id: 'ID Idealista', total_inquiries: 'Total Solicitudes',
  },
  pt: {
    my_account: 'Minha Conta', edit_profile: 'Editar Perfil', settings: 'Configurações',
    logout: 'Sair', login: 'Entrar',
    my_properties: 'Minhas Propriedades', recent_inquiries: 'Consultas Recentes',
    status_new: 'Novo', status_screening: 'Triagem', status_kyc_pending: 'KYC Pendente',
    status_qualified: 'Qualificado', status_rejected: 'Rejeitado', status_rented: 'Alugado',
    tenant_profile: 'Perfil do Inquilino', landlord_decision: 'Decisão do Proprietário',
    review_approve_desc: 'Rever e aprovar/rejeitar esta candidatura',
    application_progress: 'Progresso da Candidatura', personal_information: 'Informação Pessoal',
    id_verification: 'Verificação de Identidade', connected_profiles: 'Perfis Conectados',
    employment_information: 'Informação de Emprego', financial_information: 'Informação Financeira',
    income_verification: 'Verificação de Rendimento', required_documents: 'Documentos Necessários',
    credit_check: 'Verificação de Crédito', financing_options: 'Opções de Financiamento',
    internal_notes: 'Notas Internas', save_notes: 'Guardar Notas',
    approve: 'Aprovar', reject: 'Rejeitar', pending: 'Pendente',
    property_information: 'Informação da Propriedade', performance_metrics: 'Métricas de Desempenho',
    rental_funnel: 'Funil de Arrendamento',
    view_document: 'Ver Documento', upload: 'Carregar', uploading: 'A carregar...',
    no_inquiries: 'Sem consultas ainda', connect_bank: 'Conectar Conta Bancária',
    bank_connected: 'Conta Bancária Conectada',
    funnel_inquiry: 'Consulta Recebida', funnel_verification: 'Verificação em Curso',
    funnel_qualified: 'Qualificado', funnel_approved: 'Aprovado', funnel_rejected: 'Rejeitado',
    modero_score: 'Pontuação de Qualificação Modero', overall_rating: 'Classificação geral do inquilino',
    add_notes_placeholder: 'Adicionar notas internas sobre este inquilino...',
    notes_saved: 'Notas guardadas com sucesso',
    in_screening: 'Em Triagem', conversion_rate: 'Taxa de Conversão',
    address: 'Endereço', city: 'Cidade', monthly_rent: 'Renda Mensal', bedrooms: 'Quartos',
    idealista_id: 'ID Idealista', total_inquiries: 'Total de Consultas',
  },
  it: {
    my_account: 'Il Mio Account', edit_profile: 'Modifica Profilo', settings: 'Impostazioni',
    logout: 'Disconnetti', login: 'Accedi',
    my_properties: 'Le Mie Proprietà', recent_inquiries: 'Richieste Recenti',
    status_new: 'Nuovo', status_screening: 'Screening', status_kyc_pending: 'KYC in Attesa',
    status_qualified: 'Qualificato', status_rejected: 'Rifiutato', status_rented: 'Affittato',
    tenant_profile: 'Profilo Inquilino', landlord_decision: 'Decisione Proprietario',
    review_approve_desc: 'Rivedi e approva/rifiuta questa candidatura',
    application_progress: 'Avanzamento Candidatura', personal_information: 'Informazioni Personali',
    id_verification: 'Verifica Identità', connected_profiles: 'Profili Collegati',
    employment_information: 'Informazioni Lavorative', financial_information: 'Informazioni Finanziarie',
    income_verification: 'Verifica Reddito', required_documents: 'Documenti Richiesti',
    credit_check: 'Controllo Credito', financing_options: 'Opzioni di Finanziamento',
    internal_notes: 'Note Interne', save_notes: 'Salva Note',
    approve: 'Approva', reject: 'Rifiuta', pending: 'In Attesa',
    property_information: 'Informazioni Proprietà', performance_metrics: 'Metriche di Performance',
    rental_funnel: 'Funnel di Locazione',
    view_document: 'Visualizza Documento', upload: 'Carica', uploading: 'Caricamento...',
    no_inquiries: 'Nessuna richiesta', connect_bank: 'Collega Conto Bancario',
    bank_connected: 'Conto Bancario Collegato',
    funnel_inquiry: 'Richiesta Ricevuta', funnel_verification: 'Verifica in Corso',
    funnel_qualified: 'Qualificato', funnel_approved: 'Approvato', funnel_rejected: 'Rifiutato',
    modero_score: 'Punteggio Qualificazione Modero', overall_rating: 'Valutazione complessiva inquilino',
    add_notes_placeholder: 'Aggiungi note interne su questo inquilino...',
    notes_saved: 'Note salvate con successo',
    in_screening: 'In Screening', conversion_rate: 'Tasso di Conversione',
    address: 'Indirizzo', city: 'Città', monthly_rent: 'Affitto Mensile', bedrooms: 'Camere',
    idealista_id: 'ID Idealista', total_inquiries: 'Totale Richieste',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');
  const t = (key) => translations[language]?.[key] ?? translations.en[key] ?? key;
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}